version: '2'
services:
  web:
    container_name: pytheas_tweets
    image: cortext/cortext_pytheas
    ports:
     - '5000:8080'
    volumes:
     - './simple-tweet-web-extract:/opt/pytheas_tweets'
     - './simple-tweet-web-extract/conf:/opt/pytheas_tweets/conf'
     - './simple-tweet-web-extract/twitterscrape:/opt/pytheas_tweets/twitterscrape'
    restart: always 